### ISSUE TITLE
toBest for an specific measure

### ISSUE THREAD

**Issue by heisser-jimenez** [convert-units/convert-units#174]
How I can get the best unit for a specified measure ?. I would like to be able to do this:

```
convert(1000)
      .from('l')
      .toBest({ for: ['volume'] });
```

So this should return ml or whatever it considers the best unit but only for the volume measure. instead of doing:

```
conversion(1000)
      .from('l')
      .toBest({ exclude: [...allOtherPossibilitiesExceptThenOnesIWantToConsider] });
```

Please let me know if that makes sense to you!.

**Comment by Taar** [comment]
Thanks for the question! I'm not sure I'm completely following the question.

For your first code snippet, if `toBest()` is called without any arguments, it'll return `kl` with a value of `1`. `toBest` will not return a unit outside of the measure passed to `from()`. With that said, `convert(1000).from('l')` scopes future calls to the `volume` measure and the system (which in this case is `Metric`). Therefore, if `toBest` is called like, `convert(1000).from('l').toBest()`, it'll only match a unit within the `volume` measure which is why it always returns `kl` (in this case) and not `fl-oz` or `mm`.

Unless you're asking for an `include` feature? For example:

```javascript
// This is not currently supported.
convert(1000)
    .from('l')
    .toBest({ include: ['ml', 'cm3'] });
```
