### ISSUE TITLE
Mechanism to plugin custom units/measures

### ISSUE THREAD

**Issue by dmbarry86** [convert-units/convert-units#179]
I was wondering if you would consider a feature to provide the ability for users to be able to plugin their own custom units or measures at runtime from within their own codebase. This could be through some custom object or code which somehow gets hooked in to the main package. I've not given too much thought to implementation details yet and just wanted to gather opinion first.

I see a few benefits:

* Allows users to define their own obscure/bespoke units/measures which might not be best placed in the general package.
* Allows users to quickly add and test their own units/measures without having to wait for a new version of convert-units to be released. I see a number of people have forked this repo and presumably that is to add their own. I guess partly this is because of the lack of maintenance up until recently but even so it still feels valuable to me to be able to add in my own units/measures without polluting the general package.

**Comment by Taar** [comment]
Thanks for bring this up! I agree 100%! See my thoughts and comments below (thinking aloud):

- This would require a new version `v3` as there will be breaking changes
- Would some of the current features would become obsolete? For example, would `convert().measures()` still be useful if you're now explicitly setting the supported measures?
- Detached measurements would allow for smaller packages as it would be possible to exclude the measures you're not using (tree shaking)
- Might need to redefine how measures are structured
- Fastest implementation (imo) would be to modify `convert` to accept measurements instead of using a static set
- Upgrade to a modern test runner (maybe using [ava](https://github.com/avajs/ava)?)
- More test coverage!
- Types! If folks are going to be implementing their own measures, it would be helpful if the project provided a measure type
- To minimize changes to the code base, it would be wise to configure typescript to check the current js files and add types using jsdoc comments. See this popular project for examples: [https://github.com/preactjs/preact](https://github.com/preactjs/preact)
- Type definitions should be included in the npm package (not really related to this but it will be required) instead of relying on a `@types` package

I think the first steps towards this goal would be (these are already on my todo list):
- Upgrade test runner
- Add types

Once that's complete the code base should be in a good place to start working towards this goal.

**Comment by dmbarry86** [comment]
This all sounds good to me. I hadn't considered being able to remove measures as well but that's a good idea and I can see benefit. I'm happy to help with implementation of this feature.

Regarding your todo list. If you need any support with the test suite then I'm happy to help. I'm afraid I don't have too much Typescript experience so can't help there.

**Comment by Taar** [comment]
Great! Would you be able to tackle #180 then? @dmbarry86

**Comment by dmbarry86** [comment]
> Great! Would you be able to tackle #180 then? @dmbarry86 

Yeah sure thing.

**Comment by Taar** [comment]
@dmbarry86 Can you take a look at the linked PR and let me know what you think? #194

**Comment by dmbarry86** [comment]
Will do @Taar

**Comment by dmbarry86** [comment]
I'll go through this today @Taar. Sorry for the short delay, it's been a long bank holiday weekend in the UK so I've been AFK for a few days.

**Comment by Taar** [comment]
> 
> 
> I'll go through this today @Taar. Sorry for the short delay, it's been a long bank holiday weekend in the UK so I've been AFK for a few days.

No worries at all! I hope your weekend was enjoyable and relaxing 😄
