### ISSUE TITLE
Precision lost when converting decimal values of energy

### ISSUE THREAD

**Issue by Geraj** [convert-units/convert-units#226]
When converting
convertUnits(0.000001).from('kWh').to('Wh')
I got the following value 0.0009999999999999998 instead of 0.001

A similar conversion between mt to kg works OK.
convertUnits(0.000001).from('mt').to('kg') results in 0.001
but gives incorrect value for 0.0000001 => 0.00009999999999999999

**Comment by Taar** [comment]
This isn't an issue specifically with the `energy` values but with floating point numbers (see [here](https://stackoverflow.com/questions/588004/is-floating-point-math-broken)).

Converting `0.000001 kWh` to `Wh` results in `0.0009999999999999998` because of the maths used. It would be equal to `0.000001 * 3600000 / 3600` which results in `0.0009999999999999998`.  Interestingly though, in this case if the divison is calculated first then the floating point error goes away. `0.000001 * (3600000 / 3600)` results in `0.001` (at least it does in node `16.13.0`). While this works for this case, this could cause other conversations to produce "incorrect" results.

My advice in this situation is to round the values returned to the desired precision or implemetating something like [Jest's `expect(...).toBeCloseTo(...)` method](https://jestjs.io/docs/expect#tobeclosetonumber-numdigits).

**Comment by sujit-kamireddy** [comment]
Can convert-units use exact-math underneath to avoid this issue?
