### ISSUE TITLE
Request to publish latest version to NPM

### ISSUE THREAD

**Issue by svengau** [convert-units/convert-units#228]
Hey and thanks for this really useful library. I've noticed the doc is not inline with the current published package, more particularly, it's not possible to use system as an argument here`.toBest({ system: 'imperial' })`.

Would you mind publishing a new version ?

Thanks and wish you the best for 2022.

**Comment by Taar** [comment]
The documentation will not always be inline with any of the published packages since it reflects what's currently in development or slated for a release. To see the documentation for a release, select the tag that matches the version you're using within your application. Alternatively, you can view the documentation on `npmjs.org` for the version you're using.

You're welcome to clone the repository and manually package the library if there is a feature you require that hasn't been released.

**Comment by Taar** [comment]
The latest code changes can be found here: https://www.npmjs.com/package/convert-units/v/3.0.0-beta.3
