### ISSUE TITLE
recent released v3.0.0-beta.3 breaks @bundle-stats/utils

### ISSUE THREAD

**Issue by daniele-orlando** [convert-units/convert-units#229]
Recent release of `convert-units`, the **v3.0.0-beta.3** broke @bundle-stats/utils.

I don't know exactly if it is a responsibility of _@bundle-stats/utils_ or _convert-units_, so I'm contacting both projects to understand it. Original issue (with a reproducible project) is tracked here https://github.com/relative-ci/bundle-stats/issues/1910

**Comment by Taar** [comment]
@daniele-orlando I would like to point out that the beta builds for this project are **not** stable. If a project wants to use a beta build then I recommend pinning `convert-units` to a very specific version. Otherwise, a future beta release could cause more issues.

With all that said, between version `3.0.0-beta.2` and `3.0.0-beta.3` the `toBest` method was updated because of a bug found #219 . With this fix, it's now possible for `toBest` to return `null`. It should only return `null` if the initial value is `undefined` or if all possible best values are excluded.

Looking at the `format.js` file, [line 12](https://github.com/relative-ci/bundle-stats/blob/master/packages/utils/src/utils/format.js#L12), no units are being excluded but there is no `null` check on the returned value. I recommend adding a `null` check there. However, given the fact that the project hasn't been updated since the new `convert-units` release. I think that maybe `bundle-stats` was relying on the bug that was fixed in the most recent version of `convert-units`. With all that said, my guess is that `val` is `undefined` or `null` which will result in `toBest` returning `null`. Without knowing what `val` is, it's hard to figure out what's exactly going on here.

I can assist further if you're able to provide more information as I don't have the time right now to dig any further.

**Comment by daniele-orlando** [comment]
@Taar absolutely, the point was to be sure that the change was intended and not a bug. But you confirmed that it was an intended change, so I can close this ticket. Thank you very much for your effort on this issue.

**Comment by vio** [comment]
Thanks for checking @Taar! The issue was indeed on bundle-stats side, I was using the beta without a version lock. 

I finally had some time to review the failed tests and [added checks for empty responses from `toBest`](https://github.com/relative-ci/bundle-stats/pull/2233/files). In case it helps, the tests were failing when the value was `0`.
