### ISSUE TITLE
discussion: Simplify structure of tests and workflow for creating/updating tests

### ISSUE THREAD

**Issue by rlueder** [convert-units/convert-units#253]
As I had to create additional unit tests for `massFlowRate` I noticed most (all?) of the tests under `definitions/__tests__` use the same structure that could be streamlined. I used `volumeFlowRate.test.ts` as an example as it was the largest test in the library (434 lines, 38 unit tests) (see changes on #254 ).

I was able to reduce it to 56 lines (approx. 87% smaller) at the same time making it easier to scan the file and see which tests are already in place.

Below is an example of the new test structure with my suggested changes, every `test.ts` file would follow the same format only changes would be to the `unitTests` array that would hold all the specific tests for that file.

```
import { runTests } from './index';
import measure, { VolumeFlowRateUnits } from '../volumeFlowRate';

type TestType = [
  VolumeFlowRateUnits,
  VolumeFlowRateUnits,
  number,
  number,
  boolean
];

// prettier-ignore <-- only needed to keep columns aligned as there's no rule in Prettier to disable array formatting
const unitTests: TestType[] = [
  ['cl/s',    'l/s',      25,         0.25,               true],
  ['ml/s',    'ml/s',     13,         13,                 true],
  ['Tbs/s',   'Tbs/s',    140,        140,                true],
  ['tsp/s',   'l/s',      355,        1.75,               false],
  ['yd3/h',   'm3/min',   1,          0.012742581,        false],
];

runTests(unitTests, measure);

```
Below is what `runTests` looks like, it's a simple function that takes `unitTests`  and `measure` as parameters and maps each value to individual test cases:

```
/**
 * @typedef {Array} TestType
 * @property {string} 0 - convert from
 * @property {string} 1 - convert to
 * @property {number} 2 - input
 * @property {number} 3 - result
 * @property {boolean} 4 - exact (i.e. whether to use 'toBe' or 'toBeCloseTo' matcher)
 */

type TestType = [string, string, number, number, boolean];

/**
 * @name runTests
 * @summary Maps an array of unit test values that should be run.
 * @param {...TestType[]} tests
 * @param {Measure<string, string>} measure
 * @returns void
 */

export const runTests = (
  tests: TestType[],
  measure: Measure<string, string>
) => {
  const convert = configureMeasurements({ measure });
  return tests.map((val) =>
    test(val[0] + ' to ' + val[1], () => {
      const actual: number = convert(val[2]).from(val[0]).to(val[1]);
      const result = val[3];
      const exact = val[4];
      return exact
        ? expect(actual).toBe(result)
        : expect(actual).toBeCloseTo(result);
    })
  );
};
```

Let me know if this approach makes sense and I'd be happy to apply to the rest of the test suite.

**Comment by dmbarry86** [comment]
I think I see a few things wrong with this approach but I'm currently AFK so can't confirm my suspicions. I'll report back tomorrow after running the code.

**Comment by Taar** [comment]
> I was able to reduce it to 56 lines (approx. 87% smaller) at the same time making it easier to scan the file and see which tests are already in place.

Personally I don't see the value in making the tests more dry. I personally prefer being very explicit with my tests and if that means there is a lot of code duplication, then so be it. My reasoning can be found below and also some issues with the proposed code that I wanted to highlight.

```typescript
// prettier-ignore <-- only needed to keep columns aligned as there's no rule in Prettier to disable array formatting
const unitTests: TestType[] = [
  ['cl/s',    'l/s',      25,         0.25,               true],
  ['ml/s',    'ml/s',     13,         13,                 true],
  ['Tbs/s',   'Tbs/s',    140,        140,                true],
  ['tsp/s',   'l/s',      355,        1.75,               false],
  ['yd3/h',   'm3/min',   1,          0.012742581,        false],
];

```

I disagree with the the use of `prettier-ignore`. The data is independent of one another. I don't think having the columns aligned would help me better understand what's going on. If the goal is to increase readability then I believe that using an object would be better. That way there is no guess work or having to remember what each place in the array means. It would also make typing easier and therefore, no need to prevent prettier from formatting the code.

```typescript
{ fromUnit: 'cl/s', toUnit: 'l/s', fromValue: 25, expectedResult: 0.25, exactMatch: true }
```
Which would also make the `runTest` function easier to read and remove the usage of magic numbers (that could also be fixed with tuple unpacking but I still like using an object here instead).

```typescript
export const runTests = (
  tests: TestType[],
  measure: Measure<string, string>
) => {
  return tests.map(({ fromUnit, toUnit, fromValue, expectedResult, exactMatch }) =>
    test(`${from} to ${to}`, () => {
      // Tests should not share state
      const convert = configureMeasurements({ measure });
      const actual: number = convert(fromValue).from(fromUnit).to(toUnit);
      // I don't think the test function expects a return value
      if (exactMatch) {
        expect(actual).toBe(expectedResult);
      } else {
        expect(actual).toBeCloseTo(expectedResult);
      }
    })
  );
};
```

With all that said, if I wanted to easily see which tests exist, I would use my editor to fold the test functions in the screenshot below. Some editor use other tricks that make it easy to see what tests are present in a test file.

![image](https://user-images.githubusercontent.com/702909/184551819-6effdf7a-6303-43f6-84c6-ed11a5aa61af.png)

If the goal is to be able to see what units have been tested against one another then, in my opinion, using an editor that can fold the functions would satisfy that require without the need to change the tests. And if I'm looking to know if say, `cl/s` to `l/s` has a test, I can use the search feature within my editor to find the test string `cl/s to l/s`.

This also removes some debugging features that I personally like having. For example, if a test fails, the test runner will point to the `runTest` function being the point of failure, not the piece of data that caused the failure. I can look at the test string to see which piece of data failed but I would much rather use a line number to easily jump to the failed test in my editor. The latter will require me to search the test file for the data that fail either visually or using a search feature.

**Comment by rlueder** [comment]
All fair points, appreciate the detailed feedback, I'll close the PR, thanks for the feedback!

**Comment by dmbarry86** [comment]
I concur with @Taar. My main concern was that you had consolidated lots of unit tests in to effectively one test as far as jest and the test reporting was concerned. This would make it very difficult to debug and to see exactly what tests are available. I also think you basically tried to duplicate what jest can already doing using the [test.each](https://jestjs.io/docs/api#testeachtablename-fn-timeout) syntax. The benefit of using test.each for parameterising tests is that it still gives you some level of reporting/debugging as if you had written each test individually.

**Comment by rlueder** [comment]
I didn't know about `test.each` thanks for the info!
