### ISSUE TITLE
Converting between pace and speed

### ISSUE THREAD

**Issue by selina** [convert-units/convert-units#267]
Hi! I just started using convert-units and it's been great so far. I haven't been able to figure out, though, whether it's possible to convert between pace and speed--it seems like they're entirely separate units. It also seems like this is the only pair of units that it's possible to convert between, so maybe this is a special situation? I'm guessing I need to write my own logic to handle this but just wanted to confirm first :) Thank you so much for your time!

**Comment by Taar** [comment]
There is no direct support for this since the units are in different measures. However, if you're using one of the latest beta versions it is possible to make it work. You would need to create your own measure that is a combination of the two. There is some documentation on how to create custom measures in the readme. I believe all you would need to do is figure out the ratio from each pace unit to the speed anchor unit (anchor value of 1).
