### ISSUE TITLE
publint errors for package.json

### ISSUE THREAD

**Issue by crotwell** [convert-units/convert-units#302]
Maybe be worth fixing the errors reported by publint on the package.json:

https://publint.dev/convert-units@3.0.0-beta.6

Suggest adding
"type": "module"
and reorder exports so that "types" is first, before "require" and "import". I also think "import" should be before require as order matters and should prefer import over require.

**Comment by Taar** [comment]
Sorry forgot to comment on this issue. Thanks for bringing this to my attention. I merged your PR and created a second PR #305 that fixes the remaining warnings `publint` raised.  I also added a compile step to the CI and also added `publint` so that issues can be caught and addressed. Thanks again! :)
