### ISSUE TITLE
How to Use this library with Ember

### ISSUE THREAD

**Issue by maheshheda14** [convert-units/convert-units#304]
I have tried to install and trying to import but it is giving me error. Though I am able to see this in node_modules. Please suggest me how to procceed. 

Version 2.3.3 which is shown as latest

**Comment by Taar** [comment]
Can you provide more context? Otherwise I'm not sure I can offer much help. Version `2.3.3` and `2.3.4` are pretty old, therefore it's likely that your project might be configured in a way that would make it difficult to use those versions. If that's the case then I would recommend using a beta version. Make sure to pin it to a specific version because there is no guarantee there won't be breaking changes in future beta versions.

**Comment by Taar** [comment]
Going to close this since no further information was provided.
