### ISSUE TITLE
Import definitions with commonjs is broken

### ISSUE THREAD

**Issue by campler** [convert-units/convert-units#335]
The problem I am encountering is following an upgrade to 3.0.0-beta.7
```
Cannot find module 'convert-units/definitions/all' or its corresponding type declarations.
  There are types at '.../node_modules/convert-units/lib/esm/definitions/all.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.ts (2307)
```

I am using tsconfig
```
"module": "commonjs"
"moduleResolution": "node"
```

In this commit, exports were modified but I think a copy-paste error slipped in: https://github.com/convert-units/convert-units/commit/c3b258c9d2bd4620cb9ed4d397eea20d9cbaaa2c
Specifically, the require section refers to lib/cjs for default but **lib/esm** for types.
```
"./definitions/*": {
 ...
  "require": {
    "types": "./lib/esm/definitions/*.d.ts",
    "default": "./lib/cjs/definitions/*.js"
  }
},
```

I am really not familiar with package.json module format, but I don't think this is intended.

**Comment by Taar** [comment]
The library has moved to ESM by default, therefore, the import statements in the README aren't be used if the configuration is set to `commonjs`. Which is why you're seeing that exact error. For more information see my response [here](https://github.com/convert-units/convert-units/issues/327#issuecomment-2329569828). 

That's definitely a typo, thanks for pointing that out.

Closing since the error you're seeing is related to #327
