### ISSUE TITLE
Feature Request: API for injecting custom measures

### ISSUE THREAD

**Issue by hickeroar** [convert-units/convert-units#47]
Currently the only way to add custom measures is to fork the repo and add them there, then open a PR if we want them permanently added to convert-units.

It'd be great to be able to call `convert().addMeasure('measureName', measureExports);` to add custom measures that don't already exist.

For instance, I would like a "force" measure that converts pound-feet to newton-meters. I'm currently in the process of making a PR for the "force" definition, but it'd be great to have a stop-gap while waiting for that PR to go through.

My project will also implement some custom units that are project specific and those measures wouldn't be relevant to people at-large. Being able to inject those at-will would be excellent.

**Comment by hickeroar** [comment]
One other note: I'm willing to develop this and PR it, assuming it wouldn't be flat-out rejected out of idealistic opposition, etc. 😄 If you want to give me some of your own expectations for the change as well, that would help me make sure I produce something you'd find pleasing.

**Comment by ben-ng** [comment]
I would love to merge a PR that implements this!

As for an API... I would discourage APIs that mutate the module itself, because it can lead to confusing behavior:

```
// In a.js
var convert = require('convert-units')

convert.registerMeasure({ /* foo measures */ })
convert.registerMeasure({ /* bar measures */ })

// In b.js... it's not clear where "foo" and "bar" were registered from in your codebase, and depending on what order you require things in, this code could fail:
convert(1).from('foo').to('bar')
```

I'd prefer if you had to register custom measures on an "instance" of convert... maybe something like this:

```
var convert = require('convert-units')
var customConvert = convert().register(customMeasureA, customMeasureB, ...)

convert(1).from('foo').to('bar')
```

Ideally the custom measure registration system can also be used internally, so that custom measures are defined exactly the same way as built-in measures. That'd make it easy for people to contribute to the main project, since they just have to submit their custom measure as a pull request. It'll also reduce the documentation burden because all measures would be defined in the same way.

What are you thoughts?

**Comment by ben-ng** [comment]
Another open question is whether the API should only allow you to add custom measures, or let you define _all_ the measures available:

```js
var customConvert = convert().usingMeasures(['mass', 'volume', myCustomMeasureSet])
```

So this would create an instance of `convert` that only lets you convert the built-ins mass and volume, and some custom measure.

**Comment by kevindoole** [comment]
heh, didn't even notice this issue! Anyway, we're using this for our needs and so i have a PR that possibly addresses your needs here. #54
