### ISSUE TITLE
Support for more than two systems

### ISSUE THREAD

**Issue by qyoz** [convert-units/convert-units#56]
The code "works" but the ratios are off because of the third system.
Specifically, I was adding a new definition - fuel consumption, with three systems:
imperial (gallon), us (us gallon) and metric (litre).
 `[ 'km/l', 'l/100km', 'mi/gal-us', 'gal-us/100mi', 'mi/gal-imp', 'gal-imp/100mi']`

Each system has a different ratio when compared to another, so it can't be a fixed number.

Any thoughts?

**Comment by ben-ng** [comment]
This is a really interesting use case, and I don't have a good answer for how to implement this right now. Let me know if you have any ideas.

**Comment by qyoz** [comment]
We would need to change the calculation [here](https://github.com/ben-ng/convert-units/blob/master/lib/index.js#L106) to look for a ratio per definition, something along the lines of
```
module.exports = {
    metric: metric,
    us: us,
    imperial: imperial,
    anchors: {
        us: {
            unit: 'km/l',
            ratio_metric: x,
            ratio_imperial: y
        },
        metric: {
            unit: 'mi/gal-us',
            ratio_us: z,
            ratio_imperial: l
        },
        imperial: {
            unit: 'mi/gal-imp',
            ratio_us: k,
            ratio_metric: m
        }
    }
};
```

**Comment by jiminikiz** [comment]
Definitely keeping this open, +1

**Comment by maneetgoyal** [comment]
Looking into `index.ts`, currently we are defining new units as:

```ts
export type Unit = {
  name: {
    singular: string;
    plural: string;
  };
  to_anchor: number;
  anchor_shift?: number;
};
```

A file supporting 2 different unit system looks like (from `length.ts`):

```ts
export default {
  systems: {
    metric,  // Record<string, Unit>
    imperial,  // Record<string, Unit>
  },
  anchors: {
    metric: {
      unit: 'm',
      ratio: 3.28084,
    },
    imperial: {
      unit: 'ft',
      ratio: 1 / 3.28084,
    },
  },
};
```

In the `anchors` property we are needing to specify the `ratio` that'll probably help us move from 1 system to another. Does this mean that if we introduce `n` unit systems, we will need to specify `n*(n-1)` conversion ratio for each of the systems inside the `anchors` property?

--- 

Also, instead of classifying each unit into a different object based on its parent system, how about we do the following?

```
export type Unit = {
  name: {
    singular: string;
    plural: string;
  };
  to_anchor: number;
  anchor_shift?: number;
  system: string;  // "metric" or "si" or whatever
};
```

`to_anchor` can contain the ratio specific to only 1 unit (irrespective of its "system"). And each of the definitions file can then export just a `Record<string, Unit>`, and core logic would handle the conversion across systems?

**Comment by Taar** [comment]
I think this would work well:

```js
export default {
  systems: {
    metric,
    imperial,
  },
  anchors: {
    metric: {
      imperial: {
        ratio: 3.28084,
        // Or
        // transform: (m) => i;
      },
    },
    imperial: {
      metric: {
        ratio: 1 / 3.28084,
        // transform: (i) => m;
      },
    },
  },
};
```

A three system measure would like something like this:

```js
export default {
  systems: {
    A: {
      ah: {
        // name: {},
        to_anchor: 1e+1,
      },
      a: {
        // name: {},
        to_anchor: 1,
      },
      al: {
        // name: {},
        to_anchor: 1e-1,
      },
    },
    B: {
      bh: {
        // name: {},
        to_anchor: 1e1,
      },
      b: {
        // name: {},
        to_anchor: 1,
      },
      bl: {
        // name: {},
        to_anchor: 1e-1,
      },
    },
    C: {
      ch: {
        // name: {},
        to_anchor: 1e1,
      },
      c: {
        // name: {},
        to_anchor: 1,
      },
      cl: {
        // name: {}
        to_anchor: 1e-1,
      },
    },
  },
  anchors: {
    A: {
      // unit a -> unit b
      B: {
        ratio: 2,
      },
      // unit a -> unit c
      C: {
        ratio: 3,
      },
    },
    B: {
      // unit b -> unit a
      A: {
        ratio: 1 / 2,
      },
      // unit b -> unit c
      C: {
        ratio: 3 / 2,
      },
    },
    C: {
      // unit c -> unit a
      A: {
        ratio: 1 / 3,
      },
      // unit c -> unit b
      B: {
        ratio: 2 / 3,
      },
    },
  },
};
```

The desired result is this:

```js
convert(1).from('a').to('bl') === 20
```

The thing to note here is that the ratios in the `anchors` object are used to convert the origin system base unit to the base unit of the destination system. 

```js
// a -> bl
let v = 1  // 1 a
let a_to_anchor = 1  // systems.A.a.to_anchor
let r = v * a_to_anchor
// r = 1 a
let ratio = 2  // anchors.A.B.ratio
r *= ratio
// r = 2 b
let bl_to_anchor = 1e-1  // systems.B.bl.to_anchor
r /= b_to_anchor
// r = 20 bl
```

I think this is the simplest solution and it provides the opportunity to support systems other than metric and imperial. Which is a requirement since the digital measure systems are bits and bytes.

This week I can start working on implementing this, unless someone objects to the solution above.
