### ISSUE TITLE
Add support for lookup of unit name from its abbreviation, singular, or plural.

### ISSUE THREAD

**Issue by matmar10** [convert-units/convert-units#98]
Usage: 

```js
convert().lookup('Cups')
/*
  {
    abbr: 'cup'
  , measure: 'volume'
  , system: 'imperial'
  , singular: 'Cup'
  , plural: 'Cups'
  }
*/
convert().lookup('Kilograms', 'mass')
/*
  {
    abbr: 'kg'
  , measure: 'mass'
  , system: 'metric'
  , singular: 'Kilogram'
  , plural: 'Kilograms'
  }
*/
```

**Comment by Taar** [comment]
This is supported through `describe`

```javascript
convert().describe('kg')
/*
  {
    abbr: 'kg'
  , measure: 'mass'
  , system: 'metric'
  , singular: 'Kilogram'
  , plural: 'Kilograms'
  }
*/
```

**Comment by raquelmsmith** [comment]
This only works if you have the abbreviated unit. I'd like to be able to look up by the singular or plural unit.

**Comment by Taar** [comment]
> This only works if you have the abbreviated unit. I'd like to be able to look up by the singular or plural unit.

In what case wouldn't you know what the abbreviated unit is? Is it because the user is searching for a measure?

I definitely misunderstood the original feature request - sorry about that. However, after some thought, I believe this feature does not fit within the scope of this project. If the singular and plural values are already known, wouldn't it be possible to map them to the abbreviated unit? It would also be possible to consume the measure definitions to build this mapping. Overall, I would like to keep this library as lean as possible, which means that if a feature is possible to implement outside the library's code base, then that's where it should be implemented.

**Comment by matmar10** [comment]
@Taar  This was already fixed by this PR along with unit test coverage:

https://github.com/convert-units/convert-units/pull/99/files#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1

The metadata already exists for this. It's just a matter of adding a simple accessor function.

**Comment by raquelmsmith** [comment]
> In what case wouldn't you know what the abbreviated unit is?

My data source doesn't provide abbreviated units. Additionally, unit abbreviations are not always consistent. Tablespoons, for instance, can be abbreviated as `tbsp`, `tbs`, `tbsps`, or `tb` (plus capitalization!). 

> If the singular and plural values are already known, wouldn't it be possible to map them to the abbreviated unit?

Yes, i can store all the units in an array then filter through that but it's not very elegant. That's what I'm doing now though!

If anything it seems like this library should use the less-ambiguous and less-variable singular or plural unit names. Even then you'd have to support both singular and plural though. I could settle for just being able to look up a unit by its plural and singular values, as well as abbreviation.

**Comment by matmar10** [comment]
@raquelmsmith I've created a 2.x branch that incorporates PRs that add the feature you're looking for. It's available here:
https://github.com/matmar10/convert-units

It seems the entire project has been migrated TS with a new directory structure hence the original PRs I raised 3 years ago are no longer workable for a seamless merge:
https://github.com/convert-units/convert-units/pulls?q=is%3Apr+author%3Amatmar10+is%3Aclosed

If you still need the functionality in  the 3.x version, maybe you could utilize my original PRs to raise new PRs in the 3.x codebase?

**Comment by Taar** [comment]
> @Taar  This was already fixed by this PR along with unit test coverage:
> 
> https://github.com/convert-units/convert-units/pull/99/files#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1
> 
> The metadata already exists for this. It's just a matter of adding a simple accessor function. 

Even if a PR has unit tests, follows all contribution guidelines, and passes any other project requirements, that doesn't mean the maintainers of the project have to accept the PR.

**Comment by Taar** [comment]
> My data source doesn't provide abbreviated units. Additionally, unit abbreviations are not always consistent. Tablespoons, for instance, can be abbreviated as `tbsp`, `tbs`, `tbsps`, or `tb` (plus capitalization!). 

In version 3 (current beta) this problem can be solved by defining custom measure with an abbreviation that better suits the needs of your application. It's also possible to extend the measures that ship with the library as well.

> Yes, i can store all the units in an array then filter through that but it's not very elegant. That's what I'm doing now though!

Can you provide more details? Maybe I can help figure out a different solution that's a bit more elegant. However, do note that some solutions might only be possible if you're using version 3.

> If anything it seems like this library should use the less-ambiguous and less-variable singular or plural unit names. 

I agree that the abbreviations aren't always the best. This is why supporting custom measures was placed at the highest priority. If the shipped measures aren't what you need then you can define your own.

> I could settle for just being able to look up a unit by its plural and singular values, as well as abbreviation.

I still don't think that supporting multiple key lookup is within the scope of this project. Especially since it's now possible to define custom measures.
